// <auto-generated />
using System;
using KYC360_Assignment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KYC360_Assignment.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KYC360_Assignment.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressLine = "123 Park Street",
                            City = "Kolkata",
                            Country = "India",
                            EntityId = "1"
                        },
                        new
                        {
                            Id = 2,
                            AddressLine = "456 MG Road",
                            City = "Mumbai",
                            Country = "India",
                            EntityId = "2"
                        },
                        new
                        {
                            Id = 3,
                            AddressLine = "789 Lake Road",
                            City = "Chennai",
                            Country = "India",
                            EntityId = "3"
                        },
                        new
                        {
                            Id = 4,
                            AddressLine = "101 Hill Avenue",
                            City = "Bangalore",
                            Country = "India",
                            EntityId = "4"
                        },
                        new
                        {
                            Id = 5,
                            AddressLine = "222 River Side",
                            City = "Hyderabad",
                            Country = "India",
                            EntityId = "5"
                        });
                });

            modelBuilder.Entity("KYC360_Assignment.Models.Date", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DateType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateValue")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("Dates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateType = "Birth",
                            DateValue = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = "1"
                        },
                        new
                        {
                            Id = 2,
                            DateType = "Death",
                            DateValue = new DateTime(2020, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = "2"
                        },
                        new
                        {
                            Id = 3,
                            DateType = "Birth",
                            DateValue = new DateTime(1985, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = "3"
                        },
                        new
                        {
                            Id = 4,
                            DateType = "Death",
                            DateValue = new DateTime(2010, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = "4"
                        },
                        new
                        {
                            Id = 5,
                            DateType = "Birth",
                            DateValue = new DateTime(1978, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = "5"
                        });
                });

            modelBuilder.Entity("KYC360_Assignment.Models.Entity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Deceased")
                        .HasColumnType("bit");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Entities");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Deceased = false,
                            Gender = "Male"
                        },
                        new
                        {
                            Id = "2",
                            Deceased = true,
                            Gender = "Female"
                        },
                        new
                        {
                            Id = "3",
                            Deceased = false,
                            Gender = "Male"
                        },
                        new
                        {
                            Id = "4",
                            Deceased = true,
                            Gender = "Female"
                        },
                        new
                        {
                            Id = "5",
                            Deceased = false,
                            Gender = "Male"
                        });
                });

            modelBuilder.Entity("KYC360_Assignment.Models.Name", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("Names");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EntityId = "1",
                            FirstName = "Ravi",
                            MiddleName = "Kumar",
                            Surname = "Singh"
                        },
                        new
                        {
                            Id = 2,
                            EntityId = "2",
                            FirstName = "Sneha",
                            MiddleName = "Rani",
                            Surname = "Gupta"
                        },
                        new
                        {
                            Id = 3,
                            EntityId = "3",
                            FirstName = "Amit",
                            MiddleName = "Kumar",
                            Surname = "Sharma"
                        },
                        new
                        {
                            Id = 4,
                            EntityId = "4",
                            FirstName = "Priya",
                            MiddleName = "Devi",
                            Surname = "Verma"
                        },
                        new
                        {
                            Id = 5,
                            EntityId = "5",
                            FirstName = "Vikram",
                            MiddleName = "Singh",
                            Surname = "Yadav"
                        });
                });

            modelBuilder.Entity("KYC360_Assignment.Models.Address", b =>
                {
                    b.HasOne("KYC360_Assignment.Models.Entity", null)
                        .WithMany("Addresses")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KYC360_Assignment.Models.Date", b =>
                {
                    b.HasOne("KYC360_Assignment.Models.Entity", null)
                        .WithMany("Dates")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KYC360_Assignment.Models.Name", b =>
                {
                    b.HasOne("KYC360_Assignment.Models.Entity", null)
                        .WithMany("Names")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KYC360_Assignment.Models.Entity", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Dates");

                    b.Navigation("Names");
                });
#pragma warning restore 612, 618
        }
    }
}
